(function() {var implementors = {};
implementors["selectors"] = ["impl&lt;Impl:&nbsp;<a class='trait' href='selectors/parser/trait.SelectorImpl.html' title='selectors::parser::SelectorImpl'>SelectorImpl</a>&gt; <a class='trait' href='cssparser/serializer/trait.ToCss.html' title='cssparser::serializer::ToCss'>ToCss</a> for <a class='struct' href='selectors/parser/struct.Selector.html' title='selectors::parser::Selector'>Selector</a>&lt;Impl&gt;","impl&lt;Impl:&nbsp;<a class='trait' href='selectors/parser/trait.SelectorImpl.html' title='selectors::parser::SelectorImpl'>SelectorImpl</a>&gt; <a class='trait' href='cssparser/serializer/trait.ToCss.html' title='cssparser::serializer::ToCss'>ToCss</a> for <a class='struct' href='selectors/parser/struct.ComplexSelector.html' title='selectors::parser::ComplexSelector'>ComplexSelector</a>&lt;Impl&gt;","impl <a class='trait' href='cssparser/serializer/trait.ToCss.html' title='cssparser::serializer::ToCss'>ToCss</a> for <a class='enum' href='selectors/parser/enum.Combinator.html' title='selectors::parser::Combinator'>Combinator</a>","impl&lt;Impl:&nbsp;<a class='trait' href='selectors/parser/trait.SelectorImpl.html' title='selectors::parser::SelectorImpl'>SelectorImpl</a>&gt; <a class='trait' href='cssparser/serializer/trait.ToCss.html' title='cssparser::serializer::ToCss'>ToCss</a> for <a class='enum' href='selectors/parser/enum.SimpleSelector.html' title='selectors::parser::SimpleSelector'>SimpleSelector</a>&lt;Impl&gt;","impl&lt;Impl:&nbsp;<a class='trait' href='selectors/parser/trait.SelectorImpl.html' title='selectors::parser::SelectorImpl'>SelectorImpl</a>&gt; <a class='trait' href='cssparser/serializer/trait.ToCss.html' title='cssparser::serializer::ToCss'>ToCss</a> for <a class='struct' href='selectors/parser/struct.AttrSelector.html' title='selectors::parser::AttrSelector'>AttrSelector</a>&lt;Impl&gt;","impl&lt;Impl:&nbsp;<a class='trait' href='selectors/parser/trait.SelectorImpl.html' title='selectors::parser::SelectorImpl'>SelectorImpl</a>&gt; <a class='trait' href='cssparser/serializer/trait.ToCss.html' title='cssparser::serializer::ToCss'>ToCss</a> for <a class='struct' href='selectors/parser/struct.Namespace.html' title='selectors::parser::Namespace'>Namespace</a>&lt;Impl&gt;","impl&lt;Impl:&nbsp;<a class='trait' href='selectors/parser/trait.SelectorImpl.html' title='selectors::parser::SelectorImpl'>SelectorImpl</a>&gt; <a class='trait' href='cssparser/serializer/trait.ToCss.html' title='cssparser::serializer::ToCss'>ToCss</a> for <a class='struct' href='selectors/parser/struct.LocalName.html' title='selectors::parser::LocalName'>LocalName</a>&lt;Impl&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
